// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kreativ.kerp.domain.report;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect IndividualReport_Roo_Configurable {
    
    declare @type: IndividualReport: @Configurable;
    
}
