// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kreativ.kerp.domain.hist;

import com.kreativ.kerp.domain.hist.EmployeeHistDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EmployeeHistIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EmployeeHistIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EmployeeHistIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: EmployeeHistIntegrationTest: @Transactional;
    
    @Autowired
    private EmployeeHistDataOnDemand EmployeeHistIntegrationTest.dod;
    
    @Test
    public void EmployeeHistIntegrationTest.testCountEmployeeHists() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeHist' failed to initialize correctly", dod.getRandomEmployeeHist());
        long count = com.kreativ.kerp.domain.hist.EmployeeHist.countEmployeeHists();
        org.junit.Assert.assertTrue("Counter for 'EmployeeHist' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EmployeeHistIntegrationTest.testFindEmployeeHist() {
        com.kreativ.kerp.domain.hist.EmployeeHist obj = dod.getRandomEmployeeHist();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeHist' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeHist' failed to provide an identifier", id);
        obj = com.kreativ.kerp.domain.hist.EmployeeHist.findEmployeeHist(id);
        org.junit.Assert.assertNotNull("Find method for 'EmployeeHist' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'EmployeeHist' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EmployeeHistIntegrationTest.testFindAllEmployeeHists() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeHist' failed to initialize correctly", dod.getRandomEmployeeHist());
        long count = com.kreativ.kerp.domain.hist.EmployeeHist.countEmployeeHists();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'EmployeeHist', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.kreativ.kerp.domain.hist.EmployeeHist> result = com.kreativ.kerp.domain.hist.EmployeeHist.findAllEmployeeHists();
        org.junit.Assert.assertNotNull("Find all method for 'EmployeeHist' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'EmployeeHist' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EmployeeHistIntegrationTest.testFindEmployeeHistEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeHist' failed to initialize correctly", dod.getRandomEmployeeHist());
        long count = com.kreativ.kerp.domain.hist.EmployeeHist.countEmployeeHists();
        if (count > 20) count = 20;
        java.util.List<com.kreativ.kerp.domain.hist.EmployeeHist> result = com.kreativ.kerp.domain.hist.EmployeeHist.findEmployeeHistEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'EmployeeHist' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'EmployeeHist' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EmployeeHistIntegrationTest.testFlush() {
        com.kreativ.kerp.domain.hist.EmployeeHist obj = dod.getRandomEmployeeHist();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeHist' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeHist' failed to provide an identifier", id);
        obj = com.kreativ.kerp.domain.hist.EmployeeHist.findEmployeeHist(id);
        org.junit.Assert.assertNotNull("Find method for 'EmployeeHist' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEmployeeHist(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'EmployeeHist' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeHistIntegrationTest.testMerge() {
        com.kreativ.kerp.domain.hist.EmployeeHist obj = dod.getRandomEmployeeHist();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeHist' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeHist' failed to provide an identifier", id);
        obj = com.kreativ.kerp.domain.hist.EmployeeHist.findEmployeeHist(id);
        boolean modified =  dod.modifyEmployeeHist(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.kreativ.kerp.domain.hist.EmployeeHist merged = (com.kreativ.kerp.domain.hist.EmployeeHist) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'EmployeeHist' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeHistIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeHist' failed to initialize correctly", dod.getRandomEmployeeHist());
        com.kreativ.kerp.domain.hist.EmployeeHist obj = dod.getNewTransientEmployeeHist(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeHist' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'EmployeeHist' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'EmployeeHist' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EmployeeHistIntegrationTest.testRemove() {
        com.kreativ.kerp.domain.hist.EmployeeHist obj = dod.getRandomEmployeeHist();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeHist' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeHist' failed to provide an identifier", id);
        obj = com.kreativ.kerp.domain.hist.EmployeeHist.findEmployeeHist(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'EmployeeHist' with identifier '" + id + "'", com.kreativ.kerp.domain.hist.EmployeeHist.findEmployeeHist(id));
    }
    
}
