// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kreativ.kerp.reference;

import java.lang.String;

privileged aspect Mst_job_role_Roo_JavaBean {
    
    public String Mst_job_role.getJob_role() {
        return this.job_role;
    }
    
    public void Mst_job_role.setJob_role(String job_role) {
        this.job_role = job_role;
    }
    
}
