// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kreativ.kerp.reference;

import java.lang.String;

privileged aspect Mst_job_status_Roo_JavaBean {
    
    public String Mst_job_status.getJob_status() {
        return this.job_status;
    }
    
    public void Mst_job_status.setJob_status(String job_status) {
        this.job_status = job_status;
    }
    
}
